'''
Conatents used in module_2
'''

# Used to convert the ethnicity names to be identical between MIMIC and eICU DBs
ETHNICITY_DICT = {
    "AMERICAN INDIAN/ALASKA NATIVE": "Other/Unknown",
    "ASIAN": "Other/Unknown",
    "ASIAN - ASIAN INDIAN": "Other/Unknown",
    "ASIAN - CAMBODIAN": "Other/Unknown",
    "ASIAN - CHINESE": "Other/Unknown",
    "ASIAN - VIETNAMESE": "Other/Unknown",
    "ASIAN - OTHER": "Other/Unknown",
    "BLACK/AFRICAN": "African American",
    "BLACK/AFRICAN AMERICAN": "African American",
    "BLACK/CAPE VERDEAN": "African American",
    "BLACK/HAITIAN": "African American",
    "HISPANIC OR LATINO": "Hispanic",
    "HISPANIC/LATINO - COLOMBIAN": "Hispanic",
    "HISPANIC/LATINO - MEXICAN": "Hispanic",
    "HISPANIC/LATINO - DOMINICAN": "Hispanic",
    "HISPANIC/LATINO - GUATEMALAN": "Hispanic",
    "HISPANIC/LATINO - PUERTO RICAN": "Hispanic",
    "MIDDLE EASTERN": "Other/Unknown",
    "MULTI RACE ETHNICITY": "Other/Unknown",
    "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER": "Other/Unknown",
    "OTHER": "Other/Unknown",
    "PATIENT DECLINED TO ANSWER": "Other/Unknown",
    "PORTUGUESE": "Other/Unknown",
    "UNABLE TO OBTAIN": "Other/Unknown",
    "UNKNOWN/NOT SPECIFIED": "Other/Unknown",
    "WHITE": "Caucasian",
    "WHITE - BRAZILIAN": "Caucasian",
    "WHITE - OTHER EUROPEAN": "Caucasian",
    "WHITE - RUSSIAN": "Caucasian"
}

# Used to convert the microbiology events names to be identical between MIMIC and eICU DBs
MICROBIOLOGY_DICT = {
    "SPUTUM": "Sputum, Expectorated",
    "ANORECTAL/VAGINAL CULTURE": "Rectal Swab",
    "ABSCESS": "Other",
    "ASPIRATE": "Other",
    "BILE": "Other",
    "BIOPSY": "Other",
    "BONE MARROW": "Other",
    "BONE MARROW - CYTOGENETICS": "Other",
    "BRONCHIAL BRUSH - PROTECTED": "Other",
    "BRONCHIAL WASHINGS": "Other",
    "DIALYSIS FLUID": "Other",
    "Direct Antigen Test for Herpes Simplex Virus Types 1 & 2": "Other",
    "DIRECT ANTIGEN TEST FOR VARICELLA-ZOSTER VIRUS": "Other",
    "EYE": "Other",
    "FLUID,OTHER": "Other",
    "FOOT CULTURE": "Other",
    "FOREIGN BODY": "Other",
    "IMMUNOLOGY": "Other",
    "Immunology (CMV)": "Other",
    "Influenza A/B by DFA": "Other",
    "JOINT FLUID": "Other",
    "Mini-BAL": "Other",
    "MRSA SCREEN": "Other",
    "Rapid Respiratory Viral Screen & Culture": "Other",
    "Staph aureus Screen": "Other",
    "SWAB": "Other",
    "VIRAL CULTURE: R/O CYTOMEGALOVIRUS": "Other",
    "URINE": "Urine, Catheter Specimen",
    "CATHETER TIP-IV": "Urine, Catheter Specimen",
    "THROAT CULTURE": "Sputum, Tracheal Specimen",
    "THROAT FOR STREP": "Sputum, Tracheal Specimen",
    "TRACHEAL ASPIRATE": "Sputum, Tracheal Specimen",
    "CSF;SPINAL FLUID": "CSF",
    "Blood (CMV AB)": "Blood, Venipuncture",
    "Blood (EBV)": "Blood, Venipuncture",
    "Blood (Malaria)": "Blood, Venipuncture",
    "Blood (Toxo)": "Blood, Venipuncture",
    "BLOOD CULTURE": "Blood, Venipuncture",
    "BLOOD CULTURE ( MYCO/F LYTIC BOTTLE)": "Blood, Venipuncture",
    "SEROLOGY/BLOOD": "Blood, Venipuncture",
    "NEOPLASTIC BLOOD": "Blood, Venipuncture",
    "FLUID RECEIVED IN BLOOD CULTURE BOTTLES": "Blood, Venipuncture",
    "Stem Cell - Blood Culture": "Blood, Venipuncture",
    "BRONCHOALVEOLAR LAVAGE": "Bronchial Lavage",
    "FLUID WOUND": "Wound, Decubitus",
    "STOOL": "Stool",
    "STOOL (RECEIVED IN TRANSPORT SYSTEM)": "Stool",
    "URINE,KIDNEY": "Urine, Voided Specimen",
    "PLEURAL FLUID": "Pleural Fluid",
    "PERITONEAL FLUID": "Peritoneal Fluid",
    "TISSUE": "Skin",
}

# Used to remove non human value from the lab results
HUMAN_RANGES = {
    "age": (0, 120),
    "BMI": (10, 80),
    "WEI": (0, 250),
    "A1C": (0, 240),
    "A1CB": (0, 24),
    "ALB": (0, 100),
    "ALT": (0, 20000),
    "AST": (0, 20000),
    "IBIL": (0, 20),
    "DBIL": (0, 20),
    "BNP": (0, 10000),
    "BRE": (1, 100),
    "BUN": (2, 200),
    "Calcium, Total": (0, 20),
    "CKMB": (0, 10000),
    "CO2tV": (0, 100),
    "CPK": (0, 10000),
    "CRP": (0, 1000),
    "Creatinine": (0, 20),
    "DBP": (20, 240),
    "DDM": (0, 50),
    "FER": (0, 20000),
    "FIB": (0, 1500),
    "FIO2": (20, 100),
    "Glucose": (0, 2000),
    "HCO3": (0, 100),
    "Hemoglobin": (2, 25),
    "INR": (0.5, 5),
    "LCT": (0.2, 15),
    "LDH": (0, 50000),
    "LYM(#)": (0, 20),
    "Lymphocytes": (0.2, 100),
    "NEU(#)": (0.1, 60),
    "Neutrophils": (0.2, 100),
    "NRBC": (0, 100),
    "OSB": (50, 500),
    "OSU": (50, 2000),
    "PAO2": (0, 1000),
    "PAO2V": (0, 1000),
    "pCO2": (0, 150),
    "PEEP": (0, 20),
    "pH": (6.6, 7.8),
    "Platelet Count": (0, 1000),
    "PLTM": (0, 1000),
    "Potassium": (1, 10),
    "PTSec": (5, 50),
    "PTT": (5, 200),
    "PUL": (10, 300),
    "Red Blood Cells": (1, 8),
    "RDW": (5, 40),
    "RRM": (1, 30),
    "RRP": (1, 60),
    "SBP": (40, 250),
    "Sodium": (110, 200),
    "SpO2": (5, 100),
    "SUTUR": (5, 100),
    "SUTURO": (5, 100),
    "TBIL": (0, 20),
    "Temperature C": (20, 43),
    "TRG": (10, 2000),
    "TRP": (1, 40000),
    "TVM": (100, 1000),
    "TVP": (100, 3500),
    "VB1": (10, 100),
    "VB12": (100, 2500),
    "WBC": (0.2, 100)
}

FEATURES_FOR_MODEL_A = ['age', 'drug_ALBUTEROL']

FEATURES_FOR_MODEL_B = ['estimated_age', 'drug_ALBUTEROL']
